import { Geist, Cairo } from "next/font/google";
import "./globals.css";
import "react-lite-youtube-embed/dist/LiteYouTubeEmbed.css";

//import comoponentes
import Footer from "./_componts/Footer";
import NavBar from "./_componts/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
});

export const metadata = {
  title: "Clean Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={`${geistSans.variable} ${cairo.variable}`}>
        <NavBar></NavBar>
        {children}
        <Footer />
      </body>
    </html>
  );
}
